logging:
  level:
    ROOT: INFO
server:
  port: 9090
spring:
  data:
    mongodb:
      host: localhost:27017
      database: shop
jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad
  validityInMs: 3600000
